### ISSUE TITLE
`class func` not supported

### ISSUE THREAD

**Issue by nmoersch-calimoto** [Brightify/Cuckoo#521]
I know that `static` methods can't be overridden and are unsupported. But when one `class func` function exists in a class that should be mocked, the generated Mock cannot be compiled anymore, as Cuckoo tries (and fails) to write a mock for this class func.

Mocked `class func`s can't really be used, as they would need to be called directly on the Mock-Type, which is probably not available in the tested context. And even if: Then just the mock is being tested and nothing is actually happening.

It should either be marked as unsupported and not result in compilation errors, or the problems can somehow be solved.

Input (e.g.):
````
public class func isUsingFullAccuracy() -> Bool {
    let manager: CLLocationManager = CLLocationManager()
    return manager.accuracyAuthorization == .fullAccuracy
}
````

Output:
````
override func isUsingFullAccuracy() -> Bool {
    return cuckoo_manager.call(
        "isUsingFullAccuracy() -> Bool",
        parameters: (),
        escapingParameters: (),
        superclassCall: super.isUsingFullAccuracy(),
        defaultCall: __defaultImplStub!.isUsingFullAccuracy()
    )
}
````
Compilation Errors are then:
- Method does not override any method from its superclass
  - because the `class` keyword is missing
- 2x Static member 'isUsingFullAccuracy' cannot be used on instance of type `Xyz`
  - at `superclassCall` & `defaultCall`, because its a `class func`

**Comment by stonko1994** [comment]
We are running into the same issue when migrating from v1 to v2. Looks like the SourceKit-based generator only crawled instance members and therefore ignored them, whereas now it is getting included in the generated mocks.
